trigger on push

diff --git a/.github/workflows/terraform-manual-workflow-trigger.yml b/.github/workflows/terraform-manual-workflow-trigger.yml
--- a/.github/workflows/terraform-manual-workflow-trigger.yml
+++ b/.github/workflows/terraform-manual-workflow-trigger.yml
@@ -1,80 +1,80 @@
-name: Manually workflow trigger for terraform
+# name: Manually workflow trigger for terraform
 
-on:
-  # Manual trigger workflow
-  workflow_dispatch:
-      # Inputs the workflow accepts.
-      # inputs:
-      #     environment:
-      #         description: "Environment to run the workflow"
-      #         type: environment
-      #         required: true
-env:
-  # Credentials for deployment to AWS
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  # S3 bucket for Terraform state
-  BUCKET_TF_STATE: ${{ secrets.AWS_S3_BUCKET_TF_STATE }}
-  AWS_REGION: us-east-2
-  EKS_CLUSTER: todo-eks
+# on:
+#   # Manual trigger workflow
+#   workflow_dispatch:
+#       # Inputs the workflow accepts.
+#       # inputs:
+#       #     environment:
+#       #         description: "Environment to run the workflow"
+#       #         type: environment
+#       #         required: true
+# env:
+#   # Credentials for deployment to AWS
+#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#   # S3 bucket for Terraform state
+#   BUCKET_TF_STATE: ${{ secrets.AWS_S3_BUCKET_TF_STATE }}
+#   AWS_REGION: us-east-2
+#   EKS_CLUSTER: todo-eks
 
-jobs:
-  terraform:
-    name: "Apply terraform code changes"
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./terraform
+# jobs:
+#   terraform:
+#     name: "Apply terraform code changes"
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terraform
 
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.6.3 #if specific terraform is required
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v3
+#         with:
+#           terraform_version: 1.6.3 #if specific terraform is required
 
-      - name: Tarraform init
-        id: init
-        # store information into the bucket when run terraform init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+#       - name: Tarraform init
+#         id: init
+#         # store information into the bucket when run terraform init
+#         run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
-      - name: Terraform format
-        id: fmt
-        run: terraform fmt
+#       - name: Terraform format
+#         id: fmt
+#         run: terraform fmt
 
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
+#       - name: Terraform validate
+#         id: validate
+#         run: terraform validate
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
+#       - name: Terraform plan
+#         id: plan
+#         run: terraform plan -no-color -input=false -out planfile
+#         continue-on-error: true
       
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform plan status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
         
-      - name: Terraform apply
-        id: applyStatus
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+#       - name: Terraform apply
+#         id: applyStatus
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v1
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Get Kube config file
-        id: getconfig
-        if: steps.applyStatus.outcome == 'success'
-        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
+#       - name: Get Kube config file
+#         id: getconfig
+#         if: steps.applyStatus.outcome == 'success'
+#         run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
 
-      - name: Install Ingress controller
-        if: steps.applyStatus.outcome == 'success' && steps.getconfig.outcome == 'success'
-        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+#       - name: Install Ingress controller
+#         if: steps.applyStatus.outcome == 'success' && steps.getconfig.outcome == 'success'
+#         run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
